VAR INTEGER iCount.

PROFILER:ENABLED = TRUE. 
PROFILER:DIRECTORY = "c:\temp".
PROFILER:FILE-NAME = "c:\temp\profiler.outt".
PROFILER:DESCRIPTION = "PROFILER".
PROFILER:COVERAGE = TRUE.
PROFILER:PROFILING = TRUE.

RUN extprof.p. 

PROFILER:PROFILING = FALSE.
PROFILER:WRITE-DATA().
PROFILER:ENABLED = FALSE. 

